"""
Django settings for platforma_tuvtk project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from importlib.util import find_spec
import os
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def load_env_file(env_path: Path) -> None:
    if not env_path.exists():
        return

    for raw_line in env_path.read_text().splitlines():
        line = raw_line.strip()
        if not line or line.startswith('#') or '=' not in line:
            continue
        key, value = line.split('=', 1)
        os.environ.setdefault(key.strip(), value.strip().strip('"').strip("'"))


load_env_file(BASE_DIR / '.env')


def env_bool(name: str, default: bool) -> bool:
    value = os.environ.get(name)
    if value is None:
        return default
    return value.strip().lower() in {'1', 'true', 'yes', 'on'}


def env_list(name: str, default: str = '') -> list[str]:
    raw_value = os.environ.get(name, default)
    return [value.strip() for value in raw_value.split(',') if value.strip()]


def detect_npm_bin_path() -> str:
    configured_path = os.environ.get('NPM_BIN_PATH')
    if configured_path:
        return configured_path

    local_appdata = os.environ.get('LOCALAPPDATA')
    if local_appdata:
        local_appdata_path = Path(local_appdata)

        local_node_install = local_appdata_path / 'Programs' / 'nodejs' / 'npm.cmd'
        if local_node_install.exists():
            return str(local_node_install)

        winget_packages = local_appdata_path / 'Microsoft' / 'WinGet' / 'Packages'
        for pattern in (
            'OpenJS.NodeJS.22_*',
            'OpenJS.NodeJS.LTS_*',
            'OpenJS.NodeJS_*',
        ):
            for package_dir in sorted(winget_packages.glob(pattern), reverse=True):
                npm_paths = sorted(package_dir.glob('node-v*-win-x64/npm.cmd'), reverse=True)
                if npm_paths:
                    return str(npm_paths[0])

    return 'npm'


def prepend_node_bin_to_path(npm_bin_path: str) -> None:
    npm_path = Path(npm_bin_path)
    if not npm_path.is_absolute():
        return

    node_bin_dir = str(npm_path.parent)
    current_path = os.environ.get('Path', '')
    path_entries = current_path.split(os.pathsep) if current_path else []
    if node_bin_dir not in path_entries:
        os.environ['Path'] = os.pathsep.join([node_bin_dir, *path_entries]) if path_entries else node_bin_dir


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool('DJANGO_DEBUG', True)
DEPLOYMENT_MODE = os.environ.get('DJANGO_DEPLOYMENT_MODE', 'development').strip().lower()

# SECURITY WARNING: keep the secret key used in production secret!
configured_secret_key = os.environ.get('DJANGO_SECRET_KEY', '').strip()
if DEPLOYMENT_MODE == 'container' and not configured_secret_key:
    raise ImproperlyConfigured('DJANGO_SECRET_KEY is required in container deployment mode.')
SECRET_KEY = configured_secret_key or 'django-insecure-n=_c^sf9(ovz%2lh6sr3bpc5d89(ndl#5tm_)19k+d5-k59s%b'

HAS_DJANGO_BROWSER_RELOAD = DEBUG and find_spec("django_browser_reload") is not None

ALLOWED_HOSTS = env_list('DJANGO_ALLOWED_HOSTS', '127.0.0.1,localhost,testserver')
CSRF_TRUSTED_ORIGINS = env_list('DJANGO_CSRF_TRUSTED_ORIGINS')
USE_X_FORWARDED_HOST = env_bool('DJANGO_USE_X_FORWARDED_HOST', False)
SECURE_PROXY_SSL_HEADER = (
    ('HTTP_X_FORWARDED_PROTO', 'https')
    if env_bool('DJANGO_TRUST_PROXY_HEADERS', False)
    else None
)
SECURE_SSL_REDIRECT = env_bool('DJANGO_SECURE_SSL_REDIRECT', False)
SESSION_COOKIE_SECURE = env_bool('DJANGO_SESSION_COOKIE_SECURE', False)
CSRF_COOKIE_SECURE = env_bool('DJANGO_CSRF_COOKIE_SECURE', False)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_bootstrap_icons',
    # Project apps
    'core',
    'apps.dashboard',
    'apps.planificator',
    'apps.diplome',
    'apps.media_library',
    'apps.tasks',
    'apps.flota',
    # Frontend tooling
    'tailwind',
    'theme',
]

if HAS_DJANGO_BROWSER_RELOAD:
    # Add django_browser_reload only in DEBUG mode
    INSTALLED_APPS += ["django_browser_reload"]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'core.middleware.ApplicationShellMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

if HAS_DJANGO_BROWSER_RELOAD:
    # Add django_browser_reload middleware only in DEBUG mode
    MIDDLEWARE += [
        "django_browser_reload.middleware.BrowserReloadMiddleware",
    ]

ROOT_URLCONF = 'platforma_tuvtk.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.application_shell',
            ],
        },
    },
]

WSGI_APPLICATION = 'platforma_tuvtk.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('POSTGRES_DB', 'platforma_tuvtk'),
        'USER': os.environ.get('POSTGRES_USER', 'postgres'),
        'PASSWORD': os.environ.get('POSTGRES_PASSWORD', 'postgres'),
        'HOST': os.environ.get('POSTGRES_HOST', '127.0.0.1'),
        'PORT': os.environ.get('POSTGRES_PORT', '5432'),
        # Keep connection reuse disabled on the Django dev server.
        'CONN_MAX_AGE': int(os.environ.get('POSTGRES_CONN_MAX_AGE', '0')),
        'CONN_HEALTH_CHECKS': os.environ.get(
            'POSTGRES_CONN_HEALTH_CHECKS',
            'true',
        ).lower() in {'1', 'true', 'yes', 'on'},
        # The bundled Windows cluster may have WIN1252 template databases.
        # Build Django test databases explicitly from template0 as UTF8 so
        # Romanian application content is preserved.
        'TEST': {
            'CHARSET': 'UTF8',
            'TEMPLATE': 'template0',
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Europe/Bucharest'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = Path(os.environ.get('DJANGO_STATIC_ROOT', BASE_DIR / 'staticfiles'))
MEDIA_URL = '/media/'
MEDIA_ROOT = Path(os.environ.get('DJANGO_MEDIA_ROOT', BASE_DIR / 'media'))
PRIVATE_MEDIA_ROOT = Path(
    os.environ.get('DJANGO_PRIVATE_MEDIA_ROOT', BASE_DIR / 'private_media')
)
# The stateless Word converter returns a base64-encoded document for the
# generation request. The application-level validator keeps JSON at 32 MB.
DATA_UPLOAD_MAX_MEMORY_SIZE = 40 * 1024 * 1024

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'dashboard:index'
LOGOUT_REDIRECT_URL = 'login'

TAILWIND_APP_NAME = "theme"
NPM_BIN_PATH = detect_npm_bin_path()
prepend_node_bin_to_path(NPM_BIN_PATH)
BS_ICONS_CACHE = BASE_DIR / '.bootstrap_icons_cache'
