# Generated by Django 6.0.6 on 2026-07-05 14:14

import apps.flota.validators
import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=80)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_system', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('display_order', 'name'),
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='flota_unique_maintenance_name_ci')],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('registration_number', models.CharField(max_length=20, validators=[apps.flota.validators.validate_registration_number])),
                ('vin', models.CharField(blank=True, max_length=17, validators=[apps.flota.validators.validate_vin])),
                ('brand', models.CharField(max_length=80)),
                ('model', models.CharField(max_length=80)),
                ('manufacture_year', models.PositiveSmallIntegerField(blank=True, null=True, validators=[apps.flota.validators.validate_manufacture_year])),
                ('current_mileage', models.PositiveIntegerField(default=0)),
                ('emblem', models.ImageField(blank=True, upload_to='flota/emblems/%Y/%m/', validators=[apps.flota.validators.validate_emblem])),
                ('status', models.CharField(choices=[('active', 'Activ'), ('maintenance', 'În mentenanță'), ('out_of_service', 'Indisponibil')], db_index=True, default='active', max_length=20)),
                ('archived_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_fleet_vehicles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('brand', 'model', 'registration_number'),
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('completed_on', models.DateField()),
                ('next_due_on', models.DateField(db_index=True)),
                ('mileage', models.PositiveIntegerField(blank=True, null=True)),
                ('provider', models.CharField(blank=True, max_length=160)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_fleet_maintenance_records', to=settings.AUTH_USER_MODEL)),
                ('maintenance_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='flota.maintenancetype')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='flota.vehicle')),
            ],
            options={
                'ordering': ('-completed_on', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='VehicleAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ends_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fleet_assignments_created', to=settings.AUTH_USER_MODEL)),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fleet_assignments', to=settings.AUTH_USER_MODEL)),
                ('ended_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fleet_assignments_ended', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='flota.vehicle')),
            ],
            options={
                'ordering': ('-starts_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='vehicle',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('registration_number'), name='flota_unique_registration_ci'),
        ),
        migrations.AddConstraint(
            model_name='vehicle',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('vin'), condition=models.Q(('vin', ''), _negated=True), name='flota_unique_vin_ci'),
        ),
        migrations.AddIndex(
            model_name='maintenancerecord',
            index=models.Index(fields=['vehicle', 'maintenance_type', '-completed_on'], name='flota_record_latest_idx'),
        ),
        migrations.AddConstraint(
            model_name='maintenancerecord',
            constraint=models.CheckConstraint(condition=models.Q(('next_due_on__gt', models.F('completed_on'))), name='flota_due_after_completed'),
        ),
        migrations.AddConstraint(
            model_name='vehicleassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('ends_at__isnull', True)), fields=('vehicle',), name='flota_one_open_assignment'),
        ),
        migrations.AddConstraint(
            model_name='vehicleassignment',
            constraint=models.CheckConstraint(condition=models.Q(('ends_at__isnull', True), ('ends_at__gte', models.F('starts_at')), _connector='OR'), name='flota_assignment_ends_after_start'),
        ),
    ]
