# Generated by Django 6.0.6 on 2026-07-05 14:16

from django.db import migrations


SYSTEM_TYPES = (
    ("itp", "ITP", 10),
    ("insurance", "Asigurare", 20),
    ("oil_change", "Schimb ulei", 30),
    ("service", "Service", 40),
)


def seed_system_types(apps, schema_editor):
    MaintenanceType = apps.get_model("flota", "MaintenanceType")
    for code, name, display_order in SYSTEM_TYPES:
        MaintenanceType.objects.update_or_create(
            code=code,
            defaults={
                "name": name,
                "display_order": display_order,
                "is_active": True,
                "is_system": True,
            },
        )


def remove_system_types(apps, schema_editor):
    MaintenanceType = apps.get_model("flota", "MaintenanceType")
    MaintenanceType.objects.filter(code__in=[item[0] for item in SYSTEM_TYPES]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_system_types, remove_system_types),
    ]
