# Generated by Django 6.0.6 on 2026-07-03 16:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diplome', '0002_millimeter_coordinate_system'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='diplomatemplate',
            name='category',
            field=models.CharField(default='General', max_length=80),
        ),
        migrations.AddIndex(
            model_name='diplomatemplate',
            index=models.Index(fields=['owner', 'category', '-updated_at'], name='dipl_tmpl_owner_cat_upd'),
        ),
    ]
