# Generated by Django 6.0.6 on 2026-07-04

import apps.media_library.models
import apps.media_library.storage
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [(migrations.swappable_dependency(settings.AUTH_USER_MODEL))]

    operations = [
        migrations.CreateModel(
            name="MediaAsset",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=160)),
                ("original_filename", models.CharField(max_length=255)),
                ("file", models.FileField(max_length=500, storage=apps.media_library.storage.PrivateMediaStorage(), upload_to=apps.media_library.models.media_asset_upload_to)),
                ("kind", models.CharField(choices=[("raster", "Imagine raster"), ("svg", "SVG")], max_length=16)),
                ("extension", models.CharField(max_length=8)),
                ("mime_type", models.CharField(max_length=64)),
                ("size_bytes", models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ("width_px", models.PositiveIntegerField(blank=True, null=True)),
                ("height_px", models.PositiveIntegerField(blank=True, null=True)),
                ("sha256", models.CharField(editable=False, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("owner", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="media_library_assets", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ("-created_at", "name"),
                "indexes": [
                    models.Index(fields=["owner", "-created_at"], name="media_owner_created"),
                    models.Index(fields=["owner", "name"], name="media_owner_name"),
                ],
            },
        ),
    ]
