# Generated by Django 6.0.6 on 2026-07-02 16:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificator', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleGeneration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.PositiveSmallIntegerField()),
                ('selected_months', models.JSONField(default=list)),
                ('holidays', models.JSONField(default=list)),
                ('random_seed', models.PositiveBigIntegerField()),
                ('schedule', models.JSONField(default=list)),
                ('source_course_count', models.PositiveIntegerField()),
                ('generated_entry_count', models.PositiveIntegerField()),
                ('source_file_name', models.CharField(max_length=255)),
                ('source_file_digest', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='appsetting',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planificator_settings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='appsetting',
            name='scope',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='appsetting',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', True)), fields=('scope',), name='unique_global_planificator_setting'),
        ),
        migrations.AddConstraint(
            model_name='appsetting',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user', 'scope'), name='unique_user_planificator_setting'),
        ),
        migrations.AddField(
            model_name='schedulegeneration',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_generations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='schedulegeneration',
            index=models.Index(fields=['owner', 'created_at'], name='plan_gen_owner_created'),
        ),
    ]
